travis:
  secure:
    BINSTAR_TOKEN: k7zrr4IMsPJ7XKx/rOg0V8XAZyoEo1OabPc7l6vuByN1XqRFARODlXXcNGBmeJqHglFDZh8BOecygNU0D9AATg1bbnbNp4JL3g67XkCpBRxOEaSQaEMvzD6rcOhexL2SWYSR+GUcSfQoXWAXudKEq/RfXOKEme1+CxW+UgN8F7StsY2YN1sdiFccOMffhSzgBQBr9brRHXdz0/h9SbZnch/fu9p1jdK9PFY9aSnCQZm6KlSelmPTtaePVVpdpTVGRYIxUmUiifZOb++u0XRqUK1+zDsRIW1aHtt8KMf8IjV0o2guX0VPoqOGN3jzES0dkz6JqWz43+7v5MZ7uvUW34CmAzhXRdZS03/0HWyTByWbEVJ1ye+3c0tFjCru/sJdhyn9ps6F0//sEV1e64FjLGQXGjmuZNTa+6FF6J2ggcOdKfU1m6jMWRv9sBzs3M97mL5q/arH/CtoHxvMvPo4rV3ob4V24c0HyM8Al0ijdCQvkz20htgjduDP87Ukbg7iBYHDn+JvX7XP4kWwIY0lxvsu1JxQHhzcN0memP45Cvit2dR93H/DktdVeUaktAfNIqTjaJPuxrOx7q/8VWk9ffNh6rZeYKblPGRn+7SQHGLGNVEq4afjvmb6/u9S002sVlcAHVE+QYfgMn1Pb0Iw9cIxs/FRLwkJvRDWKmM8Bo8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
