travis:
  secure:
    BINSTAR_TOKEN: aonqqmV/d3D+9pahuJe7Gdi+Q3JE7DG0fc3nHMsqTWJzDC5X9/YMlicvkc8wd+tfPNXxF4r2pvKjXF7NJ5MqcJmZ1tVvCIIK7oUv4ZuMA0zNkH6hAM2kU+PvWVlQ9yGKKIR8BWhMd2tje5bEisjsGeNQXBUW7TBP0H2UPY21tu6kd9V97m2CapBh3hfWIUsUm7hGGctsm9RfwVWsvbQJMeVGb8pNPWI7jvcQDxLcNaO8gAIihH624gapPNlV04Cj4cJ/ilEjtnWgQpEY+sS2pM+LOYt//9phgzkMOypeD4GnoZ8b3lLJhZIq93OyhZGp2ees+/vsjC9bIPyz23/vTMG7NW49AVb2ptYeuKXPxLy38T3PQMnjjX27e8NXmGoPkahNpcUJGW/YJKAAYFstgJ3dOOa7+gKj7HI8fGMkkdoz6EIsK8nrwfi6zMgXboDyrmCLgkUQPuuVaw5hYJZ/Cch7CNOwM0ugjX67l/507rw0slB8S0B5ScO7oqcheDc2kk3+2+ufXwZDVTd6y+tpBQTWi4P2v2ccFJcGsS4iOrISzvDnqNGM65/vnyMJTm+Wfzw7UHGQOLtJ6jDY/B3ikHHK9L0+A0dkvITbExmTg3ZbaGeUYlmjfh8H1ZfT9Z19mZJjKbr27J/b8jVzPhZU48kC2xPeaJUkaWhqi2fNH2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
